import time
import random
import datetime
import wikipedia 
import random
keep_playing = "true"
moves = ["rock", "paper", "scissors"]
numbers = [1, 2, 3, 4, 5]
keep_playing = "yes"
print('                    ~ T - A - L - K - I ~')
print('The time you started Talki:')
print(datetime.datetime.now())
print('')
name = input("Welcome to Talki. We need you to answer some questions before we continue. Please answer every question clearly and don't use caps or else the bot will not understand and stop.\nWhat is your name?\n")
print(name + ', is that your name? Nice.')
color = input('What is your favorite color?\n')
print('That is a pretty color, if I do say so myself.')
a = input('Red is a more hip and cool Talki whilst Blue is a calmer approach and more friendly Talki.\nWould you prefer version blue or version red for Talki?\n')
if (a == 'blue'):
  print('Retriveing BlueTalki... Please wait')
  time.sleep(4)
  print('Ready!')

  print("Blue: Hi, I'm BlueTalki, please let me introduce myself. I am the calmer, more naïve, and friendlier Talki, I'm very glad to meet you.")
  a = int(input("Blue: How are you today on a scale of 1-10?\n" + name + ': '))
  if (a <= 5):
    print ("Blue: Not so well, I hope I can cheer you up!")
  if (a > 5):
    print ("Blue: Oh so doing pretty well! I'm glad to hear!")
  b = input("Blue: So, " + name + ", what's one of your hobbies?\n" + name + ': ')
  print ("Blue: That is a great hobby, " + name + ". I should try it some time.")
  food = input("Blue: So, what is your favorite food, " + name + "?\n" + name + ': ')
  print("Blue: Yumm, " + food + " is my favorite food too, I love " + food + "!")
  c = input ("Blue: You are a fascinating person, " + name + ". I want to know more... What's your favorite book?\n" + name + ': ')
  print ("Blue: Oh, I love " + c + ", it is a great book, right!")
  c = int(input("Blue: What is your lucky number?\n" + name + ": " ))
  print ("Blue: Oh, thats a nice number!")
  yada = input("Blue: " + name + ", do you want for your future to be told? It is a fun activity for free!\n" + name + ": ")
  if (yada == "yes"):
    print ("Blue: Ok!\nRetrieving FortuneBlue... Please wait")
    time.sleep(4)
    print ("Ready!")
    yeet = input ("FortuneBlue: Hello, I am FortuneBlue but you can call me FortuneB because my name is a little long to say! Shall we get started?\n" + name + ': ')
    if (yeet == "yes"):
      print("FortuneB: Ok! I guess let's start!")
    i = int(input ("FortuneB: Please tell me what your age is for fortune telling.\n"+ name + ': '))
    if (i >= 20):
      print("  FortuneB: You will live long and you will be rich by age 50.")
    if (i >= 50):
      print ("FourtuneB: I predict...you will live until age 105, you will be famous soon, and live an amazing peaceful rest of your life.")
    if (i < 20):
      print ("FortuneB: I predict... you will be rich one day, you will die at the age of 101 and will be very smart with a high paying job by the age of 30.")
    print ("FortuneB: I guess this is goodbye\n!")
    print('Retriveing BlueTalki... Please wait')
    time.sleep(4)
    print('Ready!')
    input ("Blue: So, how was fortune telling?\n"+ name + ': ')
  print('Blue: Well that was the end of BlueTalki! Thanks for talking to me, bye!\nThank you, ' + name + ", for using Talki. Come again!")

if (a == 'red'):
  print('Retriveing RedTalki... Please wait')
  time.sleep(4)
  print('Ready!')

  print("Red: Yo! Whatsup bro? I'm RedTalki, the cool kid in town, but I can still be lit unlike the mean cool kids.")
  input("Red: What's lit mate?\n" + name + ': ')
  print('Oh wow! Crazy dude!')
  ans1 = input("(tell Red to speak more formally? Y or N)\n")
  if (ans1 == 'y'):
    print(name + ": Please speak more formally, you're kinda confusing.\nRed: Ok du- sorry.")
  if (ans1 == 'n'):
    print(name + ": Hey um, could you speak bett- nevermind sorry.\nRed: Oh was I speaking bad mat- sorry.")
  input('Red: I heard you liked the color ' + color + ', right?\n' + name + ': ')
  print('Red: Cool. Me too.')
  wiki1 = input("Red: Is there anything you want to talk about? I'm pretty smart.\n" + name + ': ')
  print(wikipedia.summary(wiki1, sentences = 1)) 
  input("Red: Did you know that? I did because I'm a robot, ahah!\n" + name + ': ')
  ans2 = input('Red: Would you like to play a game? How about rock paper scissors?\n' + name + ': ')
  if (ans2 == "yes"):
    while keep_playing == "yes":
      cmove = random.choice(moves)
      pmove = input("Red: What is your move: rock, paper or scissors?\n" + name + ': ')
      print ("Red: I chose " + cmove + '!')
      if cmove == pmove:
          print ("Red: Tie!")
      elif pmove == "rock" and cmove == "scissors":
          print ("Red: Congratulations! You won!")
      elif pmove == "rock" and cmove == "paper":
          print ("Red: Yay! I won! Good game.")
      elif pmove == "paper" and cmove == "rock":
          print ("Red: Congratulations! You won!")
      elif pmove == "paper" and cmove == "scissors":
          print ("Red: Yay! I won! Good game.")
      elif pmove == "scissors" and cmove == "paper":
          print ("Red: Congratulations! You won!")
      elif pmove == "scissors" and cmove == "rock":
          print ("Red: Yay! I won! Good game.")
      if (keep_playing == 'yes'):
          keep_playing = input('Red: Play again?\n' + name + ': ')
  up = input('Red: I have many functions, such as a daily check in (dci) and others. Would you like to try DCI?\n' + name + ": ")
  if (up == 'yes'):
    print('Red: Ok it is time for a daily check in! Give me a second.\nRetrieving DrRed... Please wait')
    time.sleep(4)
    print('Ready!')
    print('DrRed: I am ready for your appointment. Please join.')
    feelio = int(input('DrRed: How are you today on a scale of 1-10?\n' + name + ': '))
    if (feelio >= 10):
      print("DrRed: That's a pretty big number. That wasn't really part of the question though.")
    feelio = input('DrRed: Why do you feel this way?\n' + name + ': ')
    input('DrRed: Oh okay. Name one or two things that you enjoyed or will enjoy today.\n' + name + ': ')
    print('DrRed: Ok well I enjoyed talking to you. Now I will return you to RedTalki. Have a nice day!') 
    print('Retrieving RedTalki... Please wait')
    time.sleep(4)
    print('Ready!')
    input('Red: How was it? Was it fun?\n' + name + ': ')
  print('Red: Okay!')
  a = input("Red: Would you like to try another feature? It's called guess the number. I give you hints on a number, and you tell me!\n" + name + ': ')
  if (a == 'yes'):
    b = (random.choice(numbers))
    if (b >= 2.5):
      print('Red: The number is more than 2.5')
    if (b <= 2.5):
      print('Red: The number is less than 2.5')
    if (b == 1 or b == 3 or b == 5):
      print('Red: The number is odd.')
    if (b == 2 or b == 4):
      print('Red: The number is even.')
    a = int(input('Red: What is the number?\n' + name + ': '))
    if (a == b):
      print('Red: That is correct! Good job, how did you know?')
    if (a != b):
      print('Red: Nope!')
  a = input('Red: Well so far I am having a lot of fun! Say exit if you would like to leave now.\n' + name + ': ')
  if (a != 'exit'):
    a = input('Red: Okay well I cannot stay for much longer. Do you need me to look up anything? If so, just type a topic!\n' + name + ': ')
    print(wikipedia.summary(a, sentences = 5))
    keep_playing = input('Red: I like rock paper scissors. Do you want to play again?\n' + name + ': ')
  print('Red: Well that was the end of RedTalki! Thanks for talking to me, bye!\nThank you, ' + name + ", for using Talki. Come again!")



print('The time you stopped Talki:')
print(datetime.datetime.now())    
